variable "location" {}
variable "rgname" {}
variable "vnet1name" {}
variable "vnet1range" {}
variable "vnet2name" {}
variable "vnet2range" {}
variable "vnet3name" {}
variable "vnet3range" {}
variable "gtwsubnetname" {}
variable "gtwsubnetrange" {}
variable "subnet1name" {}
variable "subnet1range" {}
variable "vpnpipname" {}
variable "vpnname" {}
variable "vpniprange" {}
variable "vpnsku" {}
variable "rootcertfile" {}
variable "tags" {
    default = {}
}